/// <reference types="node" />
import nodemailer from 'nodemailer';
import { BuilderBrief } from '../types/brief';
import dotenv from 'dotenv';

dotenv.config();

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.example.com',
  port: parseInt(process.env.SMTP_PORT || '587'),
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASS,
  },
});

function formatBriefToHtml(brief: BuilderBrief): string {
  const { executiveSummary, keyObservations, meaning, founderFocus } = brief;

  const observationsHtml = keyObservations.map(obs => `<li>${obs}</li>`).join('');
  const focusHtml = founderFocus.map(focus => `<li>${focus}</li>`).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        h1 { color: #111; font-size: 24px; margin-bottom: 20px; }
        h2 { color: #444; font-size: 18px; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        p { margin-bottom: 15px; }
        ul { margin-bottom: 15px; padding-left: 20px; }
        li { margin-bottom: 8px; }
        .footer { margin-top: 40px; font-size: 12px; color: #888; text-align: center; }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>FounderOS Builder Brief</h1>
        <p>A neutral reflection of your building process.</p>

        <h2>Executive Summary</h2>
        <p>${executiveSummary}</p>

        <h2>Key Observations</h2>
        <ul>${observationsHtml}</ul>

        <h2>What This Likely Means</h2>
        <p>${meaning}</p>

        <h2>Builder Focus (Next 7 Days)</h2>
        <ol>${focusHtml}</ol>

        <div class="footer">
          Generated by FounderOS • The OS for AI Builders • ${new Date().toLocaleDateString()}
        </div>
      </div>
    </body>
    </html>
  `;
}

export async function sendBriefEmail(brief: BuilderBrief): Promise<void> {
  const recipient = process.env.FOUNDER_EMAIL;

  if (!recipient || !process.env.SMTP_USER) {
    console.log("⚠️ Email credentials or recipient not set. Skipping email send.");
    console.log("--- MOCK EMAIL PREVIEW ---");
    console.log(formatBriefToHtml(brief).substring(0, 200) + "...");
    return;
  }

  try {
    const info = await transporter.sendMail({
      from: '"FounderOS" <founderos@example.com>',
      to: recipient,
      subject: `FounderOS Builder Brief - ${new Date().toLocaleDateString()}`,
      html: formatBriefToHtml(brief),
    });
    console.log(`📧 Email sent: ${info.messageId}`);
  } catch (error) {
    console.error("❌ Error sending email:", error);
  }
}
