/**
 * Roadmap Generation Engine
 *
 * Creates a 3-phase MVP roadmap from validated idea data.
 */

import * as fs from 'fs/promises';
import type { Idea, RoadmapResult, RoadmapPhase } from './cli-types.js';
import { updateIdea } from './storage.js';
import { getRoadmapMarkdownPath } from './storage-paths.js';

export const generateRoadmap = (idea: Idea, markdownPath = ''): RoadmapResult => {
  if (!idea.validation) {
    throw new Error('Idea must be validated before generating roadmap');
  }

  const timeToMVP = 8;
  const phase1Duration = Math.ceil(timeToMVP * 0.4);
  const phase2Duration = Math.ceil(timeToMVP * 0.35);

  const phases: RoadmapPhase[] = [
    {
      name: 'Phase 1: Discovery & Core MVP',
      duration: `Weeks 1-${phase1Duration}`,
      tasks: [
        'User research and validation interviews with 3-5 target users',
        'Competitive landscape research',
        'Define core user flow',
        'Build minimal clickable prototype',
        'Test with 5 users and iterate',
        'Document technical architecture',
      ],
      deliverables: [
        'User research synthesis doc',
        'Competitive analysis report',
        'Working prototype for user testing',
        'Core feature spec',
      ],
    },
    {
      name: 'Phase 2: Build & Validate',
      duration: `Weeks ${phase1Duration + 1}-${phase1Duration + phase2Duration}`,
      tasks: [
        'Implement core MVP features',
        'Set up basic backend and infrastructure',
        'Create simple analytics and tracking',
        'Integrate payment system if applicable',
        'Beta test with 10-20 target users',
        'Gather and implement feedback',
      ],
      deliverables: [
        'Working MVP product',
        'Documentation for beta testers',
        'User feedback collection template',
        'Roadmap for next phase',
      ],
    },
    {
      name: 'Phase 3: Polish & Launch',
      duration: `Weeks ${phase1Duration + phase2Duration + 1}-${timeToMVP}`,
      tasks: [
        'Fix critical bugs and UX issues',
        'Optimize performance',
        'Prepare launch messaging and positioning',
        'Set up landing page and marketing basics',
        'Run public beta or soft launch',
        'Monitor metrics and early feedback',
      ],
      deliverables: [
        'Production-ready MVP',
        'Launch page or landing site',
        'Initial metrics dashboard',
        'Post-launch growth plan',
      ],
    },
  ];

  return {
    generatedAt: new Date().toISOString(),
    estimatedTotalWeeks: timeToMVP,
    phases,
    markdownPath,
  };
};

export const roadmapToMarkdown = (idea: Idea, roadmap: RoadmapResult): string => {
  let md = `# ${idea.title} - MVP Roadmap\n\n`;

  md += '## Idea Summary\n';
  md += `**Problem**: ${idea.problemStatement}\n`;
  md += `**Target User**: ${idea.targetUser}\n`;
  md += `**Differentiator**: ${idea.differentiator}\n\n`;

  if (idea.validation) {
    const { dimensions } = idea.validation;
    md += '## Validation Summary\n';
    md += `- **Overall Score**: ${idea.validation.score}/100\n`;
    md += `- **Pain Intensity**: ${dimensions.painIntensity}/10\n`;
    md += `- **Urgency**: ${dimensions.urgency}/10\n`;
    md += `- **Willingness to Pay**: ${dimensions.willingnessToPay}/10\n`;
    md += `- **Founder Advantage**: ${dimensions.founderAdvantage}/10\n\n`;
    md += '### Recommendation\n';
    md += `${idea.validation.recommendation}\n\n`;
  }

  md += `## MVP Roadmap (${roadmap.estimatedTotalWeeks} weeks)\n\n`;

  roadmap.phases.forEach((phase) => {
    md += `### ${phase.name}\n`;
    md += `**Timeline**: ${phase.duration}\n\n`;

    md += '**Tasks**:\n';
    phase.tasks.forEach((task) => {
      md += `- [ ] ${task}\n`;
    });
    md += '\n';

    md += '**Deliverables**:\n';
    phase.deliverables.forEach((deliverable) => {
      md += `- ${deliverable}\n`;
    });
    md += '\n';
  });

  md += '---\n';
  md += `Generated by FounderOS CLI on ${roadmap.generatedAt}\n`;

  return md;
};

export const generateAndPersistRoadmap = async (idea: Idea): Promise<RoadmapResult> => {
  const markdownPath = getRoadmapMarkdownPath(idea.id);
  const roadmap = generateRoadmap(idea, markdownPath);
  const markdown = roadmapToMarkdown(idea, roadmap);

  await fs.writeFile(markdownPath, markdown);
  await updateIdea({
    ...idea,
    roadmap,
  });

  return roadmap;
};
